repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: venv/bin/ruff format
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-check
        name: ruff check
        entry: venv/bin/ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      - id: mypy
        name: mypy
        entry: venv/bin/mypy --strict
        language: system
        types: [python]
        pass_filenames: false
        args: [app, tests]

      - id: pytest
        name: pytest
        entry: venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false